### ISSUE TITLE
What is "Location" parameter?

### ISSUE THREAD

**Issue by vhugogarcia** [hansenms/LetsEncryptWebApp#2]
First of all! THANK YOU SO MUCH FOR THIS!!!

It is great to see a PS script ready to be used for Let's Encrypt, the extension has not been working as expected, so I expect this to work OK.

However, while setting up the parameters on the script to run it, I found there is a "Location" parameter, what is that? Is there an example of what should we put there? 

and when running there is an error saying: **"You must be logged into Azure to use this script"**

I could not find any help on the README.md file.

Thanks in advance

**Comment by hansenms** [comment]
Hi @vhugogarcia thanks for checking it out. I hope you can use it. 

The `Location` parameter is the Azure region where you would like to deploy, e.g. `eastus`, `westus`, etc. if you are in Azure Commercial or `usgovvirginia`, etc. if you are in Azure Government. 

I have updated the README.md file. 

Does that make sense?

**Comment by vhugogarcia** [comment]
Thanks @hansenms , This powershell script worked fantastic! I plan to use it every 3 months to renew my Let's encrypt certificate.
