### ISSUE TITLE
Get-ACMEVault errors

### ISSUE THREAD

**Issue by Staggerlee011** [hansenms/LetsEncryptWebApp#3]
Hi, 

When i run the script im getting the below errors, after clean install any ideas whats wrong?

**_cmdlet CreateLetsEncryptWebApp.ps1 at command pipeline position 1
Supply values for the following parameters:
CertificatePassword: ********
Please ad a DNS CNAME entry from mydomain.co.uk to mydomain.co.uk
Hit enter when completed.:**

Get-ACMEVault : Error resolving type specified in JSON 'ACMESharp.Vault.Profile.VaultProfile, ACMESharp.Vault'. Path '$type', line 2, position 66.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:97 char:14
+     $vault = Get-ACMEVault -VaultProfile $VaultName
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ACMEVault], JsonSerializationException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonSerializationException,ACMESharp.POSH.GetVault

New-ACMERegistration : Error resolving type specified in JSON 'ACMESharp.Vault.Profile.VaultProfile, ACMESharp.Vault'. Path '$type', line 2, position 66.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:101 char:8
+ $reg = New-ACMERegistration -VaultProfile $VaultName -Contacts mailto ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ACMERegistration], JsonSerializationException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonSerializationException,ACMESharp.POSH.NewRegistration

New-ACMEIdentifier : Error resolving type specified in JSON 'ACMESharp.Vault.Profile.VaultProfile, ACMESharp.Vault'. Path '$type', line 2, position 66.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:107 char:1
+ New-ACMEIdentifier -VaultProfile $VaultName -Dns $Fqdn -Alias $alias
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ACMEIdentifier], JsonSerializationException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonSerializationException,ACMESharp.POSH.NewIdentifier

Complete-ACMEChallenge : Error resolving type specified in JSON 'ACMESharp.Vault.Profile.VaultProfile, ACMESharp.Vault'. Path '$type', line 2, position 66.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:110 char:1
+ Complete-ACMEChallenge -VaultProfile $VaultName -IdentifierRef $alias ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Complete-ACMEChallenge], JsonSerializationException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonSerializationException,ACMESharp.POSH.CompleteChallenge

Update-ACMEIdentifier : Error resolving type specified in JSON 'ACMESharp.Vault.Profile.VaultProfile, ACMESharp.Vault'. Path '$type', line 2, position 66.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:111 char:16
+ ... allenge = $(Update-ACMEIdentifier $alias -VaultProfile $VaultName -Ch ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-ACMEIdentifier], JsonSerializationException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonSerializationException,ACMESharp.POSH.UpdateIdentifier

Cannot index into a null array.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:114 char:102
+ ... essage -match "File Path:[^\[]+\[([^\]]+)\]" | Out-Null; $Matches[1])
+                                                              ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

You cannot call a method on a null-valued expression.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:115 char:1
+ $fileComp = $challengeFile.Split("/")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Cannot index into a null array.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:116 char:108
+ ... age -match "File Content:[^\[]+\[([^\]]+)\]" | Out-Null; $Matches[1])
+                                                              ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:120 char:1
+ Create-WebAppDirectory -WebAppName $WebAppName -ResourceGroupName $Re ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:121 char:1
+ $folder = $fileComp[0] + "/" + $fileComp[1]
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Create-WebAppDirectory : Cannot bind argument to parameter 'Directory' because it is an empty string.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:122 char:97
+ ...  $WebAppName -ResourceGroupName $ResourceGroupName -Directory $folder
+                                                                   ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Create-WebAppDirectory], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Create-WebAppDirectory

Copy-FileToWebApp : Cannot bind argument to parameter 'Destination' because it is an empty string.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:125 char:102
+ ... ourceGroupName $ResourceGroupName -Destination $challengeFile -File " ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Copy-FileToWebApp], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Copy-FileToWebApp

Cannot index into a null array.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:126 char:1
+ $fileloc = $fileComp[0] + "/" + $fileComp[1] + "/web.config"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Copy-FileToWebApp : Cannot bind argument to parameter 'Destination' because it is an empty string.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:127 char:102
+ ... e -ResourceGroupName $ResourceGroupName -Destination $fileloc -File . ...
+                                                          ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Copy-FileToWebApp], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Copy-FileToWebApp

Update-ACMEIdentifier : Error resolving type specified in JSON 'ACMESharp.Vault.Profile.VaultProfile, ACMESharp.Vault'. Path '$type', line 2, position 66.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:131 char:16
+ ... allenge = $(Update-ACMEIdentifier $alias -VaultProfile $VaultName -Ch ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-ACMEIdentifier], JsonSerializationException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonSerializationException,ACMESharp.POSH.UpdateIdentifier

Submit-ACMEChallenge : Error resolving type specified in JSON 'ACMESharp.Vault.Profile.VaultProfile, ACMESharp.Vault'. Path '$type', line 2, position 66.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:135 char:5
+     Submit-ACMEChallenge -VaultProfile $VaultName -IdentifierRef $ali ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Submit-ACMEChallenge], JsonSerializationException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonSerializationException,ACMESharp.POSH.SubmitChallenge

Update-ACMEIdentifier : Error resolving type specified in JSON 'ACMESharp.Vault.Profile.VaultProfile, ACMESharp.Vault'. Path '$type', line 2, position 66.
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:139 char:16
+ ... allenge = $(Update-ACMEIdentifier $alias -VaultProfile $VaultName -Ch ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-ACMEIdentifier], JsonSerializationException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonSerializationException,ACMESharp.POSH.UpdateIdentifier

Failed to validate challenge
At C:\GIT\Let Encypt\CreateLetsEncryptWebApp.ps1:149 char:5
+     throw 'Failed to validate challenge'
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to validate challenge:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to validate challenge_

**Comment by hansenms** [comment]
Could you do a bit of debugging and figure out what the `$VaultName` is at that point in the script (line 97). Also, is `mydomain.co.uk` really a domain you control?
