### ISSUE TITLE
Failed to validate challenge error

### ISSUE THREAD

**Issue by under3415** [hansenms/LetsEncryptWebApp#5]
Hi
I am getting the following error while running the script.
Any idea how to troubleshoot this?

```
Failed to validate challenge
At C:\temp\CreateLetsEncryptWebApp.ps1:149 char:5
+     throw 'Failed to validate challenge'
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to validate challenge:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to validate challenge
```

**Comment by hansenms** [comment]
I suggest running it line by line and figure out what is going on. It could be something related to timing, timeout or something. It's hard to say based on the information available.

**Comment by under3415** [comment]
Thanks, I tried that but am not getting anything more meaningful. 

These are some things I managed to figure out.
1. Requires FTP access to site (not sFTP)
2. Requries http access, not https
3. Puts challenge files into ".well-known/acme-challenge" location. This needs to be opened for public access. 

I've changed the first 2, but third one is a bit of work. 
Could this be the reason for the failure?

Also, I am a bit worries about implications for the renewal. Perhaps it is easier and safer to use the DNS challenge method?

**Comment by hansenms** [comment]
Just getting to this. 

Sounds like you have a number of custom settings on your Web App, i.e. restriction of access and so on. In this case this might not be right option. The HTTP validation pipeline sort of requires that the lets encrypt backend can reach your site to validate that you have added the files. If you have access restrictions that that wouldn't work. 

In that case, I recommend just doing a DNS validation (not using the Web App) and uploading the cert. The DNS validation can also be automated. I have some stuff on my blog, e.g. here:

https://blogs.msdn.microsoft.com/mihansen/2018/03/05/using-app-service-environment-ase-without-a-wildcard-ssl-certificate/

**Comment by under3415** [comment]
Thanks, that's what I ended up doing a while ago 😁
